Feature/finite difference (#61)
* Implemented finite difference for orientation 3D.

* Implemented finite difference for tuples, transform, orientation 2D.

* Implemented first order integration.

* Updated the github workflow to include a test report.

* Fixed tests

* Forgot to update the permissions for the GitHub workflow

* Missed on test.

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -8,6 +8,7 @@ on:
   workflow_dispatch:
 
 permissions:
+  checks: write
   contents: read
 
 jobs:
@@ -16,19 +17,25 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
-    - name: Setup JDK 17
-      uses: actions/setup-java@v3
-      with:
-        java-version: '17'
-        distribution: 'temurin'
+      - name: Setup JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
 
-    - name: Setup Gradle
-      uses: gradle/gradle-build-action@v2
-      id: setup-gradle
-      with:
-        gradle-version: 8.5
-      
-    - name: Execute Gradle test
-      run: gradle test
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v2
+        id: setup-gradle
+        with:
+          gradle-version: 8.5
+
+      - name: Execute Gradle test
+        run: gradle test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+          detailed_summary: true
